site_name: CultureLinux
site_url: https://culturelinux.github.io/doc/

theme: 
  name: material
  language: fr
  palette:
    scheme: slate  
  #features:
  #  - navigation.tabs
  #  - navigation.tabs.sticky
  #  - navigation.indexes 
  features:
    - content.code.copy
extra:
  generator: false



markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Linux: 
    - 'Environement' : linux/environnement.md
    - 'Historique' : linux/history.md
    - 'Stockage' : linux/storage.md  
    - 'Utilisateurs' : linux/users.md    
    - 'Sudoers' : linux/sudoers.md            
    - 'Permissions' : linux/permissions.md            
    - 'Nmap' : linux/nmap.md
    - 'Security' : linux/security.md        
    - 'Gnome' : linux/gnome.md       
    - 'Rescue' : linux/rescue.md  
    - 'GRUB' : linux/grub.md        
  - Rocky: 
    - 'Network' : rocky/network.md
    - 'Firewall' : rocky/firewalld.md 
    - 'Locales' : rocky/locales.md        
  - Debian: 
    - 'Packages' : debian/packages.md       
    - 'Email' : debian/msmtp.md       
    - 'Network' : debian/network.md
    - 'Snap' : debian/snap.md     
    - 'UFW' : debian/ufw.md      
    - 'NFTables' : debian/nftables.md    
  - RaspberryPi: 
    - 'Grafana' : raspberrypi/grafana.md     
  - IA: 
    - 'Ollama' : ia/ollama.md          
  - Databases: 
    - 'MariaDB' : databases/mariadb.md    
    - 'MongoDB' : databases/mongodb.md   
    - 'SqlServer' : databases/sqlserver.md
    - 'InfluxDB' : databases/influxdb.md       
  - Monitoring:
    - 'Icinga' : monitoring/icinga.md     
    - 'VictoriaMetrics' : monitoring/victoriametrics.md      
    - 'InfluxDB' : monitoring/influxdb.md    
    - 'Grafana' : monitoring/grafana.md            
  - Virtualization:
    - 'Proxmox' : virtualization/proxmox.md      
  - 'Infra As Code': 
    - 'Ansible' : iac/ansible.md      
    - 'OpenToFu' : iac/opentofu.md   
  - 'Containers':
    - 'Docker' : containers/docker.md
  - Security:
    - 'Iptables' : security/iptables.md    
    - 'Lets Encrypt' : security/letsencrypt.md        
    - 'SSH' : security/ssh.md       
    - 'WireGuard' : security/wireguard.md    
    - 'GPG' : security/gpg.md  
    - 'StepCA' : security/stepca.md        
  - Git:
    - 'CLI' : git/git.md    
    - 'Gitlab' : git/gitlab.md        
  - Services:
    - 'MinIO' : services/minio.md      
  - Web: 
    - 'Nginx' : web/nginx.md     
